using Microsoft.EntityFrameworkCore;
using PiShotProject.ClassDB;
using PiShotProject.Models;
using PiShotProject.Repositories;

namespace TestPiShot;

[TestClass]
public class ProfileRepoTests
{
    private PiShotDBContext _context;
    private ProfileRepository _repository;

    [TestInitialize]
    public void Setup()
    {
        var options = new DbContextOptionsBuilder<PiShotDBContext>()
            .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString()).Options;

        _context = new PiShotDBContext(options);
        _repository = new ProfileRepository(_context);
    }

    [TestCleanup]
    public void Cleanup()
    {
        _context.Database.EnsureDeleted();
        _context.Dispose();
    }

    #region GetAllProfiles

    [TestMethod]
    public async Task GetAllProfiles_ShouldReturnAllProfiles()
    {
        // Arrange
        _context.Profiles.Add(new Profile("Alice", "img1.jpg"));
        _context.Profiles.Add(new Profile("Bob", "img2.jpg"));
        _context.SaveChanges();

        // Act
        var result = await _repository.GetAllProfilesAsync();

        // Assert
        Assert.AreEqual(2, result.Count);
        Assert.IsTrue(result.Any(p => p.Name == "Alice"));
        Assert.IsTrue(result.Any(p => p.Name == "Bob"));
    }

    [TestMethod]
    public async Task GetAllProfiles_emptyDb_ShouldReturnEmptyList()
    {
        // Act
        var result = await _repository.GetAllProfilesAsync();

        // Assert
        Assert.IsNotNull(result);
        Assert.AreEqual(0, result.Count);
    }

    #endregion

    #region GetProfileById

    [TestMethod]
    public async Task GetProfileById_ExistingId_ShouldReturnProfile()
    {
        // Arrange
        var profile = new Profile("Charlie", "img.jpg") { Id = 10 };
        _context.Profiles.Add(profile);
        await _context.SaveChangesAsync();

        // Act
        var result = await _repository.GetProfileByIdAsync(10);

        // Assert
        Assert.IsNotNull(result);
        Assert.AreEqual("Charlie", result.Name);
    }

    [TestMethod]
    public async Task GetProfileById_nonExistingId_ShouldReturnNull()
    {
        // Arrange
        _context.Profiles.Add(new Profile("Dave", "img.jpg") { Id = 5 });
        await _context.SaveChangesAsync();

        // Act
        var result = await _repository.GetProfileByIdAsync(99);

        // Assert
        Assert.IsNull(result);
    }

    #endregion

    #region AddProfile

    [TestMethod]
    public async Task AddProfile_ValidProfile_ShouldAddToDatabase()
    {
        // Arrange
        var newProfile = new Profile("Eve", "eve-jpg");

        // Act
        var result = await _repository.AddProfileAsync(newProfile);

        // Assert
        Assert.AreNotEqual(0, result.Id, "ID should be generated by DB");
        Assert.AreEqual(1, _context.Profiles.Count());
        Assert.AreEqual("Eve", _context.Profiles.First().Name);
    }

    [TestMethod]
    public async Task AddProfile_ShouldResetIdToZero()
    {
        // Arrange
        // Even if we pass an ID, the repository code explicitly sets it to 0
        var newProfile = new Profile("Frank", "frank.jpg") { Id = 999 };

        // Act
        var result = await _repository.AddProfileAsync(newProfile);

        // Assert
        // Entity Framework In-Memory will assign the next available ID (likely 1),
        // verifying that the 99 was ignored/reset.
        Assert.AreNotEqual(999, result.Id);
    }

    [TestMethod]
    public async Task AddProfile_NullImage_ShouldSetDefaultImage()
    {
        // Arrange
        var newProfile = new Profile { Name = "Grace", ProfileImage = null };

        // Act
        var result = await _repository.AddProfileAsync(newProfile);

        // Assert
        Assert.AreEqual(Profile.DefaultProfileImagePath, result.ProfileImage);
        Assert.AreEqual(Profile.DefaultProfileImagePath, _context.Profiles.First().ProfileImage);
    }

    [TestMethod]
    public async Task AddProfile_EmptyImage_ShouldSetDefaultImage()
    {
        // Arrange
        var newProfile = new Profile { Name = "Heidi", ProfileImage = "" };

        // Act
        var result = await _repository.AddProfileAsync(newProfile);

        // Assert
        Assert.AreEqual(Profile.DefaultProfileImagePath, result.ProfileImage);
    }

    #endregion

    #region UpdateProfile

    [TestMethod]
    public async Task UpdateProfile_ExistingId_ShouldUpdateAndReturnProfile()
    {
        // Arrange
        int id = 1;
        var original = new Profile("Ivan", "old.jpg") { Id = id };
        _context.Profiles.Add(original);
        await _context.SaveChangesAsync();

        var updates = new Profile("Ivan The Great", "new.jpg");

        // Act
        var result = await _repository.UpdateProfileAsync(updates, id);

        // Assert
        Assert.AreEqual("Ivan The Great", result.Name);
        Assert.AreEqual("new.jpg", result.ProfileImage);

        // Verify DB state
        var dbRecord = await _context.Profiles.FindAsync(id);
        Assert.AreEqual("Ivan The Great", dbRecord.Name);
    }

    [TestMethod]
    public async Task UpdateProfile_NonExistingId_ShouldReturnNullAndNotCrash()
    {
        // Arrange
        var updates = new Profile("Ghost", "ghost.jpg");

        // Act
        var result = await _repository.UpdateProfileAsync(updates, 999);

        // Assert
        Assert.IsNull(result);
        Assert.AreEqual(0, await _context.Profiles.CountAsync());
    }

    #endregion

    #region DeleteProfile

    [TestMethod]
    public async Task DeleteProfile_ExistingId_ShouldRemoveAndReturnProfile()
    {
        // Arrange
        int id = 1;
        var profile = new Profile("Judy", "judy.jpg") { Id = id };
        _context.Profiles.Add(profile);
        await _context.SaveChangesAsync();

        // Act
        var result = await _repository.DeleteProfileAsync(id);

        // Assert
        Assert.IsNotNull(result);
        Assert.AreEqual("Judy", result.Name);
        Assert.AreEqual(0, await _context.Profiles.CountAsync());
    }

    [TestMethod]
    public async Task DeleteProfile_NonExistingId_ShouldReturnNull()
    {
        // Arrange
        _context.Profiles.Add(new Profile("Karl", "karl.jpg"));
        await _context.SaveChangesAsync();

        // Act
        var result = await _repository.DeleteProfileAsync(999);

        // Assert
        Assert.IsNull(result);
        Assert.AreEqual(1, await _context.Profiles.CountAsync(), "Count should remain unchanged");
    }

    #endregion
}
